export enum Colors {
    red = 0,
    orange = 1,
    yellow = 2,
    darkGreen = 3,
    lightGreen = 4,
    darkBlue = 5,
    lightBlue = 6,
    skyBlue = 7,
    darkPurple = 8,
    lightPurple = 9,
    pink = 10,
    brown = 11,
    black = 12,
    darkGray = 13,
    lightGray = 14,
    white = 15,
}